### ISSUE TITLE
Linux It Works Just Bundle It 

### ISSUE THREAD

**Issue by Thomashighbaugh** [seokju-na/geeks-diary#147]
It Runs, you just gotta slap it in a deb file (not like anyone really needs much support its an API call to a GitHub Repo that edits markdown. Smart but not gonna require all that much)

**Comment by aimproxy** [comment]
Hi, I just found this app on [Electron App Directory](https://electronjs.org/apps/geeks-diary) and I find this amazing, I'm using Fedora 30 now, and the app runs very good on Node 8 (it's probably time to update), I just have some trouble with [nodegit](https://github.com/nodegit/nodegit), for Fedora you need install this:
```sh
sudo dnf install openssh-devel // For FEDORA, RHEL or CENTOS
```
And then you start all the compiling stuff from the [README](https://github.com/seokju-na/geeks-diary/blob/master/README.md)

**Comment by devvykid** [comment]
Great! I'll love to see this on .deb and .rpm👍❤🙂

**Comment by mribeirodantas** [comment]
I managed to install it in Fedora and all the setup went just fine. However, the app is not working properly.

* Developer tools are toggled by default at startup.
* File > New note does not work at all. I have to use the + button close to Note.
* Even though the commits appear to be happening, they are not being synced with the repository. Sometimes when I try to sync the application simply closes.
* Besides, when I click to move a note to the Recycle Bin, nothing happens.

I thought of creating an issue but since it's not officially supported in Linux, maybe it is better sharing it here.

**Comment by Thomashighbaugh** [comment]
or don't, its on you guys but I don't use it and so there is no need to keep the issue open.
